### ISSUE TITLE
Some detection boxes can be slightly different between filtered and unfiltered runs

### ISSUE THREAD

**Issue by KevinMcGee** [DigitalGlobe/GGD-OpenSpaceNet#222]
We've noticed some cases where detection boxes can be slightly different between two runs on the same image, where the difference is one of the runs had no filter, while the other one did.
![selection_017](https://cloud.githubusercontent.com/assets/20191880/23955973/cfb2de90-0971-11e7-8520-3412ff1a905c.png)
![selection_018](https://cloud.githubusercontent.com/assets/20191880/23955981/d637636c-0971-11e7-9082-2f2c1ccacaa7.png)
![qgis 2 18 3_025](https://cloud.githubusercontent.com/assets/20191880/23955989/dc7e9f10-0971-11e7-99de-d41479e08806.png)

**Comment by avitebskiy** [comment]
this is expected because of NMS
