### ISSUE TITLE
Issues with progress display

### ISSUE THREAD

**Issue by KevinMcGee** [DigitalGlobe/GGD-OpenSpaceNet#250]
I pulled the latest OSN from Jenkins:
-- It completes successfully with local detection, but the progress display is broken (it freezes at 0% and then immediately jumps to 100% for both reading and detecting)
--The progress display works for the web services, but after it reaches 100% for detecting it hangs forever and never completes

So, I pulled the latest from DeepCore/OSN master and built that and the bugs are completely different:
-- For local detection, the progress display works fine and it completes successfully
-- For web services it completes successfully, but the progress display is broken (again it freezes at 0% and then immediately jumps to 100% for both reading and detecting)

**Comment by geovations** [comment]
the current code does behave as he describes locally

**Comment by geovations** [comment]
So far, I'm not seeing this bug.  I get valid progress displays in both debug and release, on 2 different machines.  I'll have to see about trying this with the Jenkins build on a new machine.
